name: Run Registration Bot

on:
  workflow_dispatch:

jobs:

  run-bot:

    runs-on: ubuntu-latest

    timeout-minutes: 360

    permissions:
      contents: read

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r bots/registration_bot/requirements.txt

      - name: Run bot
        env:
          STORAGE_TOKEN: ${{ secrets.STORAGE_TOKEN }}
        run: |
          python bots/registration_bot/main.py
